language: c
before_install:
- travis/install-deps.sh
script:
- ./configure --prefix=$HOME/perm --enable-thread-safety --with-libxml --with-libxslt  CFLAGS='-O0'
  && make && make install
branches:
  only:
  - master
sudo: required
osx_image: xcode7.3
matrix:
  include:
  - os: linux
    dist: precise
  - os: linux
    dist: trusty
  - os: osx
  allow_failures:
  - os: osx
after_success:
  - travis/deploy.sh
