####################
# set up languages
language: c

####################
# install packages
before_install:
  - travis/install-deps.sh

####################
# build script
script:
  - ./configure --prefix=$HOME/perm --enable-thread-safety --with-libxml --with-libxslt  CFLAGS='-O0' && make && make install

####################
# branch configuration
branches:
  only:
  - master

####################
# os environments
#os:
#  - linux
#  - osx

sudo: required
osx_image: xcode7.3
#

####################
# build matrix
matrix:
  include:
  - { os: linux, dist: precise }
  - { os: linux, dist: trusty }
  - { os: osx }
  allow_failures:
    - os: osx
