####################
# set up languages
language: c

####################
# install packages
before_install:
  - travis/install-deps.sh

####################
# build script
script:
  - make -f Makefile.maintainer && ./configure --disable-oracle --disable-postgres && make && make check

####################
# branch configuration
branches:
  only:
  - master

####################
# os environments
#os:
#  - linux
#  - osx

sudo: required
osx_image: xcode7.3
#

####################
# build matrix
matrix:
  include:
  - { os: linux, dist: precise }
  - { os: linux, dist: trusty }
  - { os: osx }
  allow_failures:
    - os: osx
